### ISSUE TITLE
Add K8sGPT to Homelab for enhancing the CI pipeline and enabling continuous analysis

### ISSUE THREAD

**Issue by devantler** [devantler/issue-tracker#2]
**Tasklist**

- [x] devantler/oci-artifacts#203
- [x] devantler/issue-tracker#14
- [x] devantler/issue-tracker#15
- [x] devantler/issue-tracker#16
- [x] devantler/issue-tracker#17
- [x] devantler/issue-tracker#18
- [x] devantler/issue-tracker#19
- [x] devantler/issue-tracker#20
